services:
  mongo-master:
    image: mongo:latest
    container_name: mongo-master
    ports:
      - "27017:27017"
    command: mongod --replSet mongo-set --bind_ip_all
    networks:
      - mongo-net
