version: '1'
services: 
  redis-node-0:
    image: bitnami/redis-cluster:latest
    volumes:
      - 'redis-node-0_data:/bitnami/redis/data'
    environment:
      - 'REDIS_PASSWORD=1234'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4'
  
  redis-node-1:
    image: bitnami/redis-cluster:latest
    volumes:
      - 'redis-node-1_data:/bitnami/redis/data'
    environment:
      - 'REDIS_PASSWORD=1234'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4'

  redis-node-2:
    image: bitnami/redis-cluster:latest
    volumes:
      - 'redis-node-2_data:/bitnami/redis/data'
    environment:
      - 'REDIS_PASSWORD=1234'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4'

  redis-node-3:
    image: bitnami/redis-cluster:latest
    volumes:
      - 'redis-node-3_data:/bitnami/redis/data'
    environment:
      - 'REDIS_PASSWORD=1234'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4'
  
  redis-node-4:
    image: bitnami/redis-cluster:latest
    volumes:
      - 'redis-node-4_data:/bitnami/redis/data'
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
      - redis-node-3
    environment:
      - 'REDISCLI_AUTH=jacob'
      - 'REDIS_PASSWORD=1234'
      - 'REDIS_CLUSTER_REPLICAS=1'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4'
      - 'REDIS_CLUSTER_CREATOR=yes'
  
volumes:
  redis-node-0_data:
    driver: local
  redis-node-1_data:
    driver: local
  redis-node-2_data:
    driver: local
  redis-node-3_data:
    driver: local
  redis-node-4_data:
    driver: local
  